-- Create mock user in auth.users table for testing mode
-- This allows the foreign key constraints to be satisfied when using the mock user ID

INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at,
  is_anonymous
) VALUES (
  '12345678-1234-1234-1234-123456789abc'::uuid,
  '00000000-0000-0000-0000-000000000000'::uuid,
  'authenticated',
  'authenticated',
  'test-admin@example.com',
  '$2a$10$mockhashedpassword1234567890',
  now(),
  null,
  '',
  null,
  '',
  null,
  '',
  '',
  null,
  now(),
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Test Admin", "role": "admin"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null,
  false
) ON CONFLICT (id) DO NOTHING;

-- Also ensure the user has admin role in user_roles table
INSERT INTO public.user_roles (
  user_id,
  role
) VALUES (
  '12345678-1234-1234-1234-123456789abc'::uuid,
  'admin'::user_role
) ON CONFLICT (user_id, role) DO NOTHING;