// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiqmtirctaqxhqnwfuqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcW10aXJjdGFxeGhxbndmdXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODUxNjgsImV4cCI6MjA2NjI2MTE2OH0.AIgyTcnILi4lMJPQY5LUF2CGC1cVRSoLuk0baOKgvbQ";

// Testing mode flag - should match the one in useAuth.tsx
const TESTING_MODE = false;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Note: In testing mode, we rely on RLS policies that directly check for the mock user ID
// instead of using auth.uid() which requires actual JWT authentication